#!/usr/bin/env bash
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="$DIR/travonet-wg"
if [ ! -f "$BIN" ] && [ -f "$DIR/TravonetWG/travonet-wg" ]; then
    BIN="$DIR/TravonetWG/travonet-wg"
fi

CONF="${1:-$DIR/client.conf}"
if [ -n "$1" ]; then
    if [ -f "$1" ]; then
        CONF="$1"
        shift
    elif [ -f "$DIR/$1" ]; then
        CONF="$DIR/$1"
        shift
    fi
fi
EXTRA_ARGS=("$@")
IFACE="wg0"

if [ "$EUID" -ne 0 ]; then
    echo "This script requires root privileges to manage TUN, routing, and raw sockets."
    echo "Running with sudo..."
    exec sudo "$0" "$CONF" "${EXTRA_ARGS[@]}"
fi

mkdir -p /var/run/wireguard

# Extract Endpoint IP from config
ENDPOINT_IP=$(grep -i '^[[:space:]]*Endpoint' "$CONF" | head -n 1 | cut -d '=' -f2 | tr -d ' ' | cut -d ':' -f1)

# Detect default gateway and interface
DEFAULT_GW=$(ip route show default | awk '{print $3}' | head -n 1)
DEFAULT_DEV=$(ip route show default | awk '{print $5}' | head -n 1)

echo "================================================================"
echo "Starting TravonetWG with L3 Evasion"
echo "================================================================"
echo "Config:       $CONF"
echo "Extra Args:   ${EXTRA_ARGS[*]:-none}"
echo "Interface:    $IFACE"
echo "Endpoint IP:  $ENDPOINT_IP"
echo "Default GW:   $DEFAULT_GW ($DEFAULT_DEV)"
echo "================================================================"

CLEANED_UP=0
cleanup() {
    if [ "$CLEANED_UP" -eq 1 ]; then
        return
    fi
    CLEANED_UP=1

    echo ""
    echo "Stopping $IFACE and restoring system routing..."
    
    # Remove VPN routes
    ip route del 0.0.0.0/1 dev "$IFACE" 2>/dev/null || true
    ip route del 128.0.0.0/1 dev "$IFACE" 2>/dev/null || true
    if [ -n "$ENDPOINT_IP" ]; then
        ip route del "$ENDPOINT_IP/32" 2>/dev/null || true
    fi

    # Remove TUN interface
    ip link del dev "$IFACE" 2>/dev/null || true

    # Restore DNS
    if [ -f /etc/resolv.conf.travonet_bak ]; then
        cp -f /etc/resolv.conf.travonet_bak /etc/resolv.conf
        rm -f /etc/resolv.conf.travonet_bak
        echo "DNS restored."
    fi

    echo "Original routing restored cleanly."
}
trap cleanup SIGINT SIGTERM EXIT

# Start travonet-wg in the background
"$BIN" -f -d -c "$CONF" "${EXTRA_ARGS[@]}" "$IFACE" &
PID=$!

# Wait for interface to appear and come UP
echo "Waiting for interface $IFACE to be initialized..."
for i in {1..30}; do
    if ip link show dev "$IFACE" >/dev/null 2>&1; then
        break
    fi
    sleep 0.2
done

# Short pause for initial handshake completion
sleep 1.5

# Apply VPN routing rules
if [ -n "$ENDPOINT_IP" ] && [ -n "$DEFAULT_GW" ] && [ -n "$DEFAULT_DEV" ]; then
    echo "Configuring VPN routing table..."
    
    # 1. Direct host route to WireGuard endpoint via physical gateway (prevents routing loops)
    ip route replace "$ENDPOINT_IP/32" via "$DEFAULT_GW" dev "$DEFAULT_DEV"
    
    # 2. Route all internet traffic through VPN using /1 trick (overrides 0.0.0.0/0 without touching default route)
    ip route replace 0.0.0.0/1 dev "$IFACE"
    ip route replace 128.0.0.0/1 dev "$IFACE"
    
    # 3. Configure DNS (1.1.1.1)
    if [ ! -f /etc/resolv.conf.travonet_bak ]; then
        cp /etc/resolv.conf /etc/resolv.conf.travonet_bak
    fi
    echo -e "# Generated by TravonetWG\nnameserver 1.1.1.1\nnameserver 1.0.0.1" > /etc/resolv.conf
    
    echo "================================================================"
    echo "VPN IS FULLY ACTIVE"
    echo "All system internet traffic and DNS are now routed through $IFACE."
    echo "Test with: curl https://ifconfig.me"
    echo "Press Ctrl+C to disconnect and restore original routing."
    echo "================================================================"
fi

wait $PID
